name: sossho_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  intl: ^0.19.0
  #  cookie_jar: ^4.0.8
  #  dio_cookie_manager: ^3.1.1
  # flutter_sslcommerz: ^2.2.2-nullsafety.0
  sliver_tools: ^0.2.12
  timeline_tile: ^2.0.0
  pinput: ^5.0.0
  flutter_sslcommerz: ^2.3.6
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
